# Generated by Django 5.0.10 on 2025-04-30 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0070_vlangroup_vlan_id_ranges'),
        ('netbox_cloud', '0002_cloudorchestrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurevirtualnetwork',
            name='prefix',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ipam.prefix'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='azureresourcegroup',
            name='azure_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='azuresubnet',
            name='azure_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='azuresubscription',
            name='azure_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='azurevirtualnetwork',
            name='azure_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
